name: Django CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: arjun
          MYSQL_DATABASE: akhil
          MYSQL_USER: akhil
          MYSQL_PASSWORD: qwerty

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt
  
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          echo "$SSH_PRIVATE_KEY" > alma.pem
          ssh -o StrictHostKeyChecking=no -i alma.pem ubuntu@52.71.33.91 "cd /opt/ && sudo git pull origin master && source venv/bin/activate && sudo pip install -r requirements.txt && sudo python3 manage.py makemigrations && sudo python3 manage.py migtrate "
